/******************************************************************************
FIXED LABELS
******************************************************************************/
#define LBL_CONNECT       "Connect"
#define LBL_DISCONNECT    "Disconnect"
#define LBL_CONNECTING    "Connecting..."
#define LBL_DISCONNECTING "Disonnecting..."
#define LBL_SRV_MISS      "Server missing..."
#define LBL_PRT_MISS      "Port missing..."
#define LBL_CLS_MISS      "Callsign missing..."
#define LBL_LOGIN         "Login session..."
#define LBL_LOGGEDIN      "Logged in"
#define LBL_CONN_CLOSED   "Connection closed by the remote end"
#define LBL_ERR_SOCKET    "Could not create socket. Error"
#define LBL_ERR_SELECT	  "select. Error"
#define LBL_ERR_CONN      "connect failed. Error"
#define LBL_ERR_PARSE     "Error parsing dx cluster output"
#define LBL_ERR_JOIN      "ERROR; return code from pthread_join() is"
#define LBL_ERR_BAND      "Error writing bands file"
#define LBL_CONNECTED     "Connected"
