#define LBL_CONNECT       "Connect"
#define LBL_DISCONNECT    "Disconnect"
#define LBL_CONNECTING    "Connecting..."
#define LBL_DISCONNECTING "Disonnecting..."
#define LBL_SRV_MISS      "Server missing..."
#define LBL_PRT_MISS      "Port missing..."
#define LBL_CLS_MISS      "Callsign missing..."
